services:
  mq-send:
    image: ibmmq-test/send
    build: ./send
    environment:
      - LICENSE=accept
    networks:
      - mq-p2p

  mq-receive:
    image: ibmmq-test/receive
    build: ./receive
    environment:
      - LICENSE=accept
    expose:
      - "1415"
    networks:
      - mq-p2p

networks:
  mq-p2p:
