DROP TABLE IF EXISTS example_table;

CREATE TABLE example_table (
    col_bigint BIGINT,
    col_int INTEGER,
    col_smallint SMALLINT,
    col_decimal DECIMAL,
    col_numeric NUMERIC,
    col_real REAL,
    col_double_precision DOUBLE PRECISION,
    col_serial SERIAL,
    col_bigserial BIGSERIAL,
--    col_money MONEY,
    col_char CHAR(10),
    col_varchar VARCHAR(100),
    col_text TEXT,
    col_bytea BYTEA,
    col_timestamp TIMESTAMP,
    col_date DATE,
    col_time TIME,
    col_interval INTERVAL,
    col_boolean BOOLEAN
--    col_point POINT,
--    col_line LINE,
--    col_lseg LSEG,
--    col_box BOX,
--    col_path PATH,
--    col_polygon POLYGON,
--    col_circle CIRCLE,
--    col_cidr CIDR,
--    col_inet INET,
--    col_macaddr MACADDR,
--    col_macaddr8 MACADDR8,
--    col_tsvector TSVECTOR,
--    col_tsquery TSQUERY,
--    col_uuid UUID,
--    col_xml XML,
--    col_json JSON,
--    col_jsonb JSONB,
--    col_array INT[],
--    col_range INT4RANGE,
--    col_date_range DATERANGE
);
