cabal-version:      3.0
name:               xmlparse
version:            0.1.0.0
license:            Apache-2.0
license-file:       LICENSE
author:             Takayuki Uchida
maintainer:         jacobitebeerlove@gmail.com
build-type:         Simple
extra-doc-files:    CHANGELOG.md

common common-config
    ghc-options: -Wall
    build-depends:
        base ^>=4.19.2.0
      , bytestring
      , cassava
      , containers
      , text
      , vector
      , xml-conduit
    default-language: GHC2021

executable spotbugs-error
    import:           common-config
    main-is:          Main.hs
    hs-source-dirs:   spotbugs-error

executable checkstyle-config
    import:           common-config
    main-is:          Main.hs
    hs-source-dirs:   checkstyle-config
